# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  displayName: git pull
  inputs:
    script: 'git pull https://github.com/JacobBN/React-Portfolio-App.git feature'
- task: Npm@1
  displayName: npm install
  inputs:
    command: 'install'
- task: CmdLine@2
  displayName: npm run test
  inputs:
    script: 'CI=true npm run test'
- task: CmdLine@2
  displayName: git push
  inputs:
    script: 'git push https://github.com/JacobBN/React-Portfolio-App.git feature'
